### ISSUE TITLE
nitter.mstdn.social is down / redirects to mstdn.social

### ISSUE THREAD

**Issue by cboltz** [xnaas/nitter-instances#10599]
**Describe the bug**
Since about two days, nitter.mstdn.social is down. This looks intentional, because it redirects all requests to mstdn.social

**To Reproduce**
1. Go to https://nitter.mstdn.social/
2. You get redirected to https://mstdn.social/about

**Expected behavior**
A Nitter instance ;-)

Given the redirect, my _guess_ is that nitter.mstdn.social was intentionally shut down. However, I didn't find an official announcement about this.

**Comment by xnaas** [comment]
Updated https://github.com/zedeus/nitter/wiki/Instances as well.
