### ISSUE TITLE
Nitter.mint.lgbt:  Rate limited

### ISSUE THREAD

**Issue by CharaHarimata** [xnaas/nitter-instances#9074]
Upon checking, the mint.lgbt-based instance is currently saying:
```
Instance has been rate limited.
Use another instance or try again later.
```
Not 100% sure on specifics, though.

**Comment by xnaas** [comment]
Loads fine for me. ¯\\\_(ツ)_/¯

**Comment by CharaHarimata** [comment]
Ah. Might have been something to do with verification. Wouldn't be the first time something like this has happened. GSuites strikes again I suppose.
